<link href='http://fonts.googleapis.com/css?family=Bitter'
	rel='stylesheet' type='text/css' />


<?php
echo $this->headLink ()->prependStylesheet ( $this->basePath ( '/css/main.css' ) );
?>


<link rel='stylesheet' id='camera-css' href='/css/camera.css'
	type='text/css' media='all' />
<script type="text/javascript" src="/_scripts/jquery-1.7.2.min.js"></script>

<script type='text/javascript' src='/js/jquery.mobile.customized.min.js'></script>
<script type='text/javascript' src='/js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='/js/camera.min.js'></script>


<script type="text/javascript"
	src="_/scripts/jquery-ui-1.7.2.custom.min.js"></script>
<script type="text/javascript" src="/_scripts/jquery.Scrollable.min.js"></script>

<script type="text/javascript"
	src="/_scripts/jquery.scrollTo-1.4.2-min.js"></script>

<script type="text/javascript" src="/_scripts/scripts.js"></script>

<script type="text/javascript" src="/_scripts/jquery.isotope.min.js"></script>
<script type="text/javascript"
	src="/_scripts/scripts-our-work-portfolio.js"></script>



<!--[if IE 6]>
<script type="text/javascript" src="_scripts/DD_belatedPNG_0.0.8a-min.js"></script>
<script type="text/javascript">
  DD_belatedPNG.fix('.pngFix');
</script>
<![endif]-->

<!--<script type="text/javascript" src="http://use.typekit.com/fhy4tox.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>-->

<style>
#panel {
	background: #AAAA;
	/*color: #bbc7cf;*/
	padding: 15px;
}

#contenido {
	
}
</style>
<script>
		$(document).ready(function() {
			$("#galeria-titulo").html("Stands para Ferias");
			$(".screen").hide(1);
		});
</script>
<div class="row">

	<div class="span4">

		<div class="title-link">
			<a><?php echo $this->translate('Stands/Exhibits') ?></a>
		</div>
	</div>


	<div class="span5">
		<div class="contents-innerHTML clearfix">
			<div class="cs-tools-top clearfix">
				<ul class="cs-navi">
					<!-- 
		########################
		MENU SUPOERIOR - CATEGORIAS
		########################
		 -->
					<!-- <li><a href="javascript:;" id="cs-link-Featured" data-filter=".Featured" class="selected">Featured</a></li> -->
					<li><a href="javascript:;" id="cs-link-Extemin2011"
						data-filter=".Extemin2011">Extemin 2011</a></li>
					<li><a href="javascript:;" id="cs-link-Extemin2009"
						data-filter=".Extemin2009">Extemin 2009</a></li>
					<!-- <li><a href="javascript:;" id="cs-link-Expomina"
						data-filter=".Expomina">Expomina</a></li>
					<li><a href="javascript:;" id="cs-link-Excom"
						data-filter=".Excom">Excom</a></li> -->
					<li><a href="javascript:;" id="cs-link-Otras-Ferias"
						data-filter=".Otras-Ferias">Otras Ferias</a></li>

				</ul>
			</div>

		</div>
	</div>
</div>

<div class="row">
	<div class="span7">

		<div style="margin: 20px 0; font-size: 14px;">
		<?=$this->translate ( 'Soluciones de imagen corporativa y presencia comercial en ferias y eventos; brindamos soluciones integrales en arquitectura y marketing ferial. Cobertura operativa en Europa, Asia y Sudamerica.' );?></div>
	</div>
</div>






<div class="row">
	<div class="span12">
		<div id="case-study-list-container" class="case-study-list"
			style="min-height: 630px;">
			<!-- 
####################
LISTADO DE CUADRADOS Y LOGOS
####################
 -->
			<div class="case-study-item Extemin2009" id="cs-item-ferreyros_09">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2009"
				id="cs-item-angloamerican_09">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2009" id="cs-item-nissan_09">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2009" id="cs-item-petroperu_09">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2009" id="cs-item-varios_09">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-3M_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-ABB_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-Antamina_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-ferreyros_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011"
				id="cs-item-GeneralElectric_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-Liebherr_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-GoldFields_11">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-TECSUP_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>



			<div class="case-study-item Extemin2011" id="cs-item-Motaengil_11">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-Praxair_11">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-Schulz_11">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-Pecsa_11">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Extemin2011" id="cs-item-varios_11">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			
			<!-- Expomina
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Expomina"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			 -->
			
			
			
			
			
			<!-- Excom
			<div class="case-study-item Excom"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Excom"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Excom"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Excom"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"><span class="logo"></span>
				</a>
			</div>
			<div class="case-study-item Excom"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"> <span class="logo"></span>
				</a>
			</div>
			 -->
			
			
			
			

			<div class="case-study-item Otras-Ferias"
				id="cs-item-construccion_otras">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Otras-Ferias" id="cs-item-energia_otras">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Otras-Ferias" id="cs-item-mineras_otras">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>

			<div class="case-study-item Otras-Ferias" id="cs-item-otros_otras">
				<a href="javascript:;" class="thumb"> <!-- <span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span>--> <span class="logo"></span>
				</a>
			</div>
			<!-- <div class="case-study-item Featured Research" id="cs-item-sony">
								<a href="javascript:;" class="thumb"><span class="cs-info"><strong>Sony
											Creative Center and Sony Mobile: </strong>Proof of Concept and
										Usability Testing</span><span class="logo"></span></a>
							</div>  -->

			<div id="case-study-list-navi">
				<!-- NO NAVI for now -->
			</div>
			<!-- 
#######################
TEXTOS
#######################
 -->



			<div id="cs-item-screen-ferreyros_09" class="screen  Extemin2009"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body">
					<!--  Slider -->

					<!--  Slider -->
				</div>
			</div>

			<div id="cs-item-screen-angloamerican_09" class="screen  Extemin2009"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-nissan_09" class="screen  Extemin2009"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-petroperu_09" class="screen  Extemin2009"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-varios_09" class="screen  Extemin2009"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-3M_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-ABB_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Antamina_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-ferreyros_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-GeneralElectric_11"
				class="screen  Extemin2011" style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Liebherr_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-GoldFields_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-TECSUP_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Motaengil_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Praxair_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Schulz_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-Pecsa_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-varios_11" class="screen  Extemin2011"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-construccion_otras"
				class="screen  Otras-Ferias" style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-energia_otras" class="screen  Otras-Ferias"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-mineras_otras" class="screen  Otras-Ferias"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>

			<div id="cs-item-screen-otros_otras" class="screen  Otras-Ferias"
				style="display: block;">
				<a class="close-cs-item-screen">Close</a>
				<div class="screen-body"></div>
			</div>





		</div>
	</div>

</div>
<!-- class row -->
