<?php
echo $this->headLink ()->prependStylesheet ( $this->basePath ( '/css/panel.css' ) );
?>

 <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

<style type="text/css">
#panel {
}

#galeria-titulo {
  margin: 30px 40px 0 0;
}

#titulo {
  color: #A90000;
  margin: 50px 10px 0 10px;
  font-size: 25px;
}

#descripcion {
  font-size: 15px;
  margin: 30px 0 0px 10px;
}

.img_section img {
  margin : -20px 0 -2px 0;
  height: 380px;
}
hr{ padding: 0 0 0 0; margin:0 0 0 0;}
</style>

<script type="text/javascript">

 $(function() {
  
    $.widget("ui.tooltip", $.ui.tooltip, {
      options: {
        content: function () {
          return $(this).prop('title');
        }
      }
    });

  $( ".preview" ).tooltip({
    show: null,
    position: {
      my: "left top",
      at: "left bottom"
    },
    open: function( event, ui ) {
      ui.tooltip.animate({ top: ui.tooltip.position().top + 10 }, "fast" );
    }
  });
});

</script>

<div class="row">
  <div style="margin-left: 30px;">
      <h3 id="titulo" style="margin-top: 0px;">
        <?= $this->translate ( 'Stands/Exhibits' ) ?> </h3>
    <div style="font-size: 15px; margin-left: 10px; margin-top: 30px; margin-bottom: 30px;"><?= $this->translate ( 'Dise&ntilde;o y producci&oacute;n de stands y exhibiciones corporativas para ferias comerciales. Soluciones integrales en cualquier parte del mundo; contamos con operaciones en Asia, Europa y Sudam&eacute;rica gracias a nuestras afiliaciones internacionales y partnerships que  hemos construido a lo largo de nuestros m&aacute;s de diez a&ntilde;os de experiencia en el rubro.' ) ?></div>

    <a class="btn btn-success"
      href="<?=$this->url("stands"); ?>/proyectos"><?php echo $this->translate('Ver Proyectos') ?> &raquo;</a>&nbsp;&nbsp;&nbsp;
       <!-- <a class="btn btn-success preview" title='
       <table><tr><td><img src="/_images/membresias/ifes_mini.jpg" />&nbsp;&nbsp;&nbsp;<td><img src="/_images/membresias/edpa_min.jpg" />&nbsp;&nbsp;&nbsp;<td><img src="/_images/membresias/afep_mini.jpg" />
       ' href="<?=$this->url("stands"); ?>/membresias" ><?=$this->translate('Miembros de'); ?></a>&nbsp;&nbsp;&nbsp; -->
       <!--<a class="btn btn-success preview" title='
       <table><tr><td><img src="/_images/proveedores/perumin_mini.jpg" />&nbsp;&nbsp;&nbsp;<td><img src="/_images/proveedores/expoalimentaria2013_mini.jpg" />
       ' href="<?=$this->url("stands"); ?>/proveedores"><?=$this->translate('Proveedores Oficiales'); ?></a>
      -->
      <a href="<?=$this->url("stands"); ?>/proveedores" style="color:#333;text-decoration:none;" target="_blank"><?=$this->translate('Proveedores Oficiales'); ?>: 
        <img src="/_images/proveedores/perumin_mini.jpg" /> &nbsp;&nbsp;&nbsp; <img src="/_images/proveedores/expoalimentaria2013_mini.jpg" /></a>

  </div>
	<br/>
  <div style="margin-left: 30px;">
    <img src="<?=$this->basePath("images/stands.jpg")?>">
  </div>
</div>
<script>
 jQuery(function(){
  // style="text-align:center"
  $("#slogan").html("<?= $this->translate ( 'Stands / Exhibits' ) ?>");
  
 });
</script>

