<style type="text/css">
/*div.tabla {  }

div.tabla table { margin: 0 0; border-collapse: collapse; width: 80%; margin-left: 7em}*/
div.tabla table td, div.tabla table th { border: 1px solid #fff; padding: 0; text-align: justify  }
h3#titulo { color: #A90000; font-size: 25px;}

.centered { text-align: center; /*height: 180px;*/ line-height:10em }
.centered img{  }

</style>


<div class="row">

	<div class="span12 tabla">
		<h3 id="titulo"><?=$this->translate('Membres&iacute;as');?></h3>
		<p><?=$this->translate('Ser miembros de estas asociaciones, nos acredita y obliga como Empresa a cumplir con los m&aacute;s altos est&aacute;ndares internacionales de calidad y de servicios.'); ?></p>
	</div>
</div>

<div class="row">
	<div class="span2"></div>
	<div class="span2 centered"><img src="/_images/membresias/edpa.jpg" /></div>
	<div class="span6" style="text-align:justify">
	<h3>EDPA</h3>
		<?=$this->translate('La EDPA es The Exhibit Designers and Producers Association (EDPA), fundada en 1954, es una asociaci&oacute;n reconocida internacionalmente con m&aacute;s de 300 miembros corporativos de 18 pa&iacute;ses que participan en el dise&ntilde;o, fabricaci&oacute;n, transporte, instalaci&oacute;n y servicio de stands y exhibiciones para ferias y exposiciones.'); ?>
	</div>
</div>
<div class="row">
	<div class="span2"></div>
	<div class="span2 centered"><img src="/_images/membresias/ifes.jpg" /></div>
	<div class="span6" style="text-align:justify">
	<h3>IFES</h3>
		<?=$this->translate('IFES es The International Federation of Exhibition and Event services.  La federaci&oacute;n est&aacute; activa desde 1985 y desde entonces ayuda a sus miembros a tener un mejor servicio con sus clientes que participan en ferias y exhibiciones a nivel internacional.'); ?>
	</div>
</div>
<div class="row">
	<div class="span2"></div>
	<div class="span2 centered"><img src="/_images/membresias/afep.jpg" /></div>
	<div class="span6" style="text-align:justify">
	<h3>AFEP</h3>
		<?=$this->translate('La Asociaci&oacute;n de Ferias del Per&uacute;, "AFEP", agrupa a los Organizadores de Ferias Nacionales e Internacionales que se desarrollan en el Per&uacute;, autorizadas por el Ministerio de Comercio Exterior y Turismo (MINCETUR). Fundada en el 2009 se crea con el objeto de representar, coordinar, defender y fomentar las actividades feriales de sus asociados.'); ?>
	</div>
</div>


<div class="row">
	<div class="span12"> 
		<span style="float: right;">
			<a href="/stands">
				<img border="0" src="/images/volver.png">
			</a>
		</span>
	</div>

</div>