<style type="text/css">
/*div.tabla {  }

div.tabla table { margin: 0 0; border-collapse: collapse; width: 80%; margin-left: 7em}*/
div.tabla table td, div.tabla table th { border: 1px solid #fff; padding: 0; text-align: justify  }
h3#titulo { color: #A90000; font-size: 25px;}

.centered { text-align: center; /*height: 180px;*/ line-height:10em }
.centered img{  }

</style>


<div class="row">

	<div class="span12 tabla">
		<h3 id="titulo"><?=$this->translate('Proveedores Oficiales'); ?></h3>
		<p><?=$this->translate('Gracias a nuestros est&aacute;ndares de calidad y servicio, y a nuestra experiencia en el dise&ntilde;o y producci&oacute;n de stands para ferias, hemos calificado como proveedores oficiales para:'); ?></p>
	</div>

</div>




<div class="row">
	<div class="span2"></div>
	<div class="span2 centered"><img src="/_images/proveedores/perumin.jpg" /></div>
	<div class="span6" style="text-align:justify">
	<h3>PERUMIN (EXTEMIN)</h3>
	<?=$this->translate('Despu&eacute;s de una rigurosa selecci&oacute;n hemos calificado como &uacute;nico proveedor oficial de stands con homologaci&oacute;n internacional para Extemin 2013.  Esta feria congrega a los principales proveedores de la miner&iacute;a mundial. M&aacute;s de mil empresas dan a conocer sus productos y novedades en equipos y servicios, as&iacute; como los avances tecnol&oacute;gicos de la industria minera y otras actividades afines.'); ?>	
	</div>
</div>
<div class="row">
	<div class="span2"></div>
	<div class="span2 centered"><img src="/_images/proveedores/expoalimentaria2013.jpg" /></div>
	<div class="span6" style="text-align:justify">
	<h3>EXPOALIMENTARIA</h3>
		<?=$this->translate('Es la feria internacional de alimentos, bebidas, maquinaria, equipos, insumos, envases y embalajes, servicios, restaurantes y gastronom&iacute;a m&aacute;s grande de la regi&oacute;n, la cual se constituye como el punto de encuentro internacional de empresas exportadoras y compradores de los cinco continentes.'); ?>
	</div>
</div>

<div class="row">
	<div class="span12"> 
		<span style="float: right;">
			<a href="/stands">
				<img border="0" src="/images/volver.png">
			</a>
		</span>
	</div>

</div>