<?php
echo $this->doctype ();
?>

<html>
<head>
<meta charset="utf-8">
    <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>
    <?php echo $this->headTitle('Apoyo Publicitario')?>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <?php  $this->headMeta()->appendName('description', $this->layout()->description )?>
	<?php  $this->headMeta()->appendName('author', 'César Gutiérrez Tineo')?>
	<?php  $this->headMeta()->appendName('ZendFramework', \Zend\Version\Version::VERSION)?>
	<?php  $this->headMeta()->appendName('keywords', $this->layout()->keywords)?>
	<?php  $this->headMeta()->appendName('robots', 'index, follow, all')?>
	<?php  $this->headMeta()->appendName('expires', 'never')?>
	
	<?php  $this->headMeta()->appendName('revisit', '1 days')?>
	<?php  $this->headMeta()->appendName('revisit-after', '1 days')?>
	<?php  $this->headMeta()->appendName('distribution', 'global')?>
	<?php echo $this->headMeta()->appendName('generator', 'Zend Framework '.\Zend\Version\Version::VERSION)?>
	
    <!-- Le styles -->
    <?php
				
				echo $this->headLink ( array (
						'rel' => 'shortcut icon',
						'type' => 'image/vnd.microsoft.icon',
						'href' => $this->basePath ( '/images/favicon.ico' ) 
				) )->prependStylesheet ( $this->basePath ( '/css/bootstrap-responsive.min.css' ) )->prependStylesheet ( $this->basePath ( '/css/style.css' ) )->prependStylesheet ( $this->basePath ( '/css/bootstrap.min.css' ) )->prependStylesheet ( $this->basePath ( '/css/layout.css' ) )?>

    <!-- Scripts -->
    <?php
				
				echo $this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
						'conditional' => 'lt IE 9' 
				) )->prependFile ( $this->basePath () . '/js/jquery-1.7.2.min.js' )?>

<!-- <script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
	type="text/javascript"></script> -->
<script type="text/javascript">

$(function() {
	
	var $scrollingDiv = $("#scrollingDiv");

	$("#scrollingDiv")
	.css({"marginTop": ($(window).scrollTop() + $(window).height() - $("#scrollingDiv").height() -10) + "px"} );
	
	$(window).scroll(function(){			
		$scrollingDiv
			.css({"marginTop": ($(window).scrollTop() + $(window).height() - $("#scrollingDiv").height() -10) + "px"} );			
	});
	$(window).resize(function() {
		$scrollingDiv
		.css({"marginTop": ($(window).scrollTop() + $(window).height() - $("#scrollingDiv").height() ) + "px"} );

		if($(window).height()<330||$(window).width()<480){$("#scrollingDiv").hide();}
		if($(window).height()>330||$(window).width()>480){$("#scrollingDiv").show();}
	});
});
</script>
</head>

<body>
	<div id="scrollingDiv"
		style="position: absolute; width: 100%; margin: 0px; padding: 0px; z-index: 9999;">
		<div id="icono"
			style="border: solid 1px #CCC; background: #DDD; margin: 0 16%; padding: 10px;"><?php echo $this->translate('All rights reserved.')?>
		</div>
	</div>
	<section class="container">

		<header>
			<div id="banner_logo">
				<a href="<?php echo $this->url('home') ?>"><img
					src="<?php echo $this->basePath("_images/logo.jpg"); ?>" /></a>
			</div>

		</header>
	</section>


	<div class="navbar ">
		<div class="navbar-inner">
			<div class="container">
				<div>
					<ul class="nav">
						<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
						<li><a href="<?php echo $this->url('aboutus'); ?>">Qui&eacute;nes
								Somos</a></li>
						<li><a href="<?php echo	$this->url('projects'); ?>">Qué hacemos</a></li>
						<li><a href="<?php echo $this->url("stands"); ?>">Stands para ferias</a></li>
						<li><a href="<?php echo $this->url('clients'); ?>">Clientes</a></li>
						<li><a href="<?php echo $this->url('contactus'); ?>">Cont&aacute;ctanos</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>




	<div class="container">

      <?php echo $this->content; ?>

      <hr>

		<!-- <footer>
				<table>
					<tr>
						<td style="border-right: solid 2px #444;"><?php echo $this->translate('All rights reserved.') ?> - 2011 . Apoyo Publicitario <br />Planta:
							Av.Libertad 386 -L32 Perú / Of Miramar 180-L32 - Perú</td>
						<td style="border-right: solid 2px #444;">Fonos 511 717-5333 /
							566-2800 <br />ventas@apoyopublicitario.com
						</td>
						<td style="border-right: solid 2px #444;">Únete a nuestro equipo,
							<br />envíanos tu CV
						</td>
						<td></td>
					</tr>
				</table>

			</footer>-->

	</div>

	<!-- /container -->
	
  <?php echo $this->inlineScript()?>
  </body>
</html>
