<? translate("Tiendas y retailers"); ?>
<? translate("Centros y/o agencias atenci&oacute;n") ?>
<? translate("Espacios comerciales menores"); ?>
<? translate("BBVA: proyecto nueva imagen"); ?>
<? translate("Cambio de imagen BIF &#45; Ban Bif"); ?>
<? translate("Cofide: proyecto desarrollo nueva oficina"); ?>
<? translate("Interactividad para Espacios Comerciales"); ?>
<? translate("Aplicaciones para Promociones"); ?>
<? translate("Proyecto categor&iacute;a electro (SONY)"); ?>
<? translate("Proyecto categor&iacute;a gourmet (Cencosud-Wong)"); ?>
<? translate("Proyecto categor&iacute;a electrohogar (OSTER)"); ?>