<link rel='stylesheet' href='/css/galeria.css' type='text/css'
	media='all'>

<link rel='stylesheet' id='camera-css' href='/css/camera.css'
	type='text/css' media='all'>

<script type="text/javascript" src="/_scripts/jquery-1.7.2.min.js"></script>
<script type='text/javascript' src='/js/jquery.mobile.customized.min.js'></script>
<script type='text/javascript' src='/js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='/js/camera.min.js'></script>
<script type="text/javascript">
$(function(){
	$('#main-slider').camera({
		height: '400px',
		loader: 'bar',
		pagination: false,
		thumbnails: true,
		time: 4000,
		transPeriod: 1000
	});
});
</script>
<!-- 
<div>Galleria : <?=$this->galeria;?> | Secction : <?=$this->section;?></div>

<?php foreach ($this->items as $item) {?>
<div>
					data-thumb :<?=$item->getPath_thumb(); ?>|
					data-src: <?=$item->getPath(); ?>|
					<?=$item->getDescripcion(); ?>
				</div>
<?php } ?>
 -->
<div class="row">




	<div class="span3">
		<ul class="nav nav-tabs nav-stacked">
				<?php foreach ($this->secciones as $seccion) {?>
				<li id="link3"><a href="<?=$seccion->getUrl();?>"><?=$this->translate(  $seccion->getDescripcion() );?> </a></li>
				
				<?php } ?>
				
				
				 <li class="divider"></li>

		</ul>
		<a class="btn btn-success"
			href="<?=$this->url("projects"); ?>"><?php echo $this->translate('Volver') ?> 
		</a>
		<br/>
	</div>


	<div class="span9">
		<div class="camera_wrap camera_magenta_skin" id="main-slider">
						<?php foreach ($this->items as $item) { ?>
						<div data-thumb="<?=$item->getPath_thumb(); ?>"
				data-src="<?=$item->getPath(); ?>">
				<div class="camera_caption fadeFromBottom"><?=$item->getDescripcion(); ?></div>
			</div>
						<?php } ?>
					</div>
	</div>




</div>