<!-- <link rel='stylesheet' href='/css/galeria.css' type='text/css'
	media='all'> -->

<? 

$this->headLink()
->prependStylesheet ( $this->basePath ( '/css/camera.css' ) );

?>

<?
$this->headScript ()


->prependFile ( $this->basePath () . '/js/galerias.js' )
->prependFile ( $this->basePath () . '/js/camera.min.js' )
->prependFile ( $this->basePath () . '/js/jquery.easing.1.3.js' )
->prependFile ( $this->basePath () . '/js/jquery.mobile.customized.min.js' )


;	
?>	

<script type="text/javascript">
jQuery(function(){
	
	//alert(1);
});
</script>
<!-- 
<div>Galleria : <?=$this->galeria;?> | Secction : <?=$this->section;?></div>

<?php foreach ($this->items as $item) {?>
<div>
					data-thumb :<?=$item->getPath_thumb(); ?>|
					data-src: <?=$item->getPath(); ?>|
					<?=$item->getDescripcion(); ?>
				</div>
<?php } ?>
 -->
<div class="row">




	<div class="span3">
		<ul class="nav nav-tabs nav-stacked">
				<?php foreach ($this->secciones as $seccion) {?>
				<li id="link3"><a href="<?=$seccion->getUrl();?>"><?=$this->translate(  $seccion->getDescripcion() );?> </a></li>
				
				<?php } ?>
				
				
				 <li class="divider"></li>

		</ul>
		<a class="btn btn-success"
			href="<?=$this->url("projects"); ?>"><?php echo $this->translate('Volver') ?> 
		</a>
		<br/>
	</div>

	<div class="row">
	<div class="span9">
		<div class="camera_wrap camera_magenta_skin" id="main-slider">
			<?php foreach ($this->items as $item) { ?>
				<div data-thumb="<?=$item->getPath_thumb(); ?>"	data-src="<?=$item->getPath(); ?>">
				<div class="camera_caption fadeFromBottom"><?=$item->getDescripcion(); ?></div>
				</div>
				<?php } ?>
		</div>
	</div>
	</div>

</div>

<?php
		switch ($this->section) {
			case "tec" :
				$titulo = $this->translate ( "Tiendas y Espacios Comerciales" );
				break;
			
			case "pic" :
				$titulo = $this->translate ( "Proyectos de Imagen Corporativa" );
				break;
			
			case "tipv" : 
				$titulo = $this->translate ( 'Tecnolog&iacute;a e Interactividad para Puntos de Venta' );
				break;
			
			case "ptm" :
				$titulo = $this->translate ( "Proyectos de Trade Marketing" );
				break;
		}
		?>
<script>
 jQuery(function(){
	$("#slogan").html("<?=$this->translate( $titulo); ?> <br/> <h4><?=$this->translate( "$this->galeria_loaded" ); ?> </h4>");
	
 });
</script>