<?php
$titulo_pagina = " - Proyectos de Imagen Corporativa";
$select_hacemos = "select";
$tag_des = "Equipo especializado en proyectos de expansi&oacute;n a nivel nacional y cambios de imagen corporativa, est&aacute; formado por un staff de ingenieros, arquitectos y supervisores de obra con expericencia y conocimiento de las regulaciones de INDECI, defensa civil y todas las normas vigentes de seguridad, en se&ntilde;alizacion logramos el equilibrio perfecto entre el dise&ntilde;o creativo y las normas tecnicas para mantener la iamgen de su empresa.";
$tag_key = "Equipo especializado en proyectos de expansi&oacute;n a nivel nacional y cambios de imagen corporativa, est&aacute; formado por un staff de ingenieros, arquitectos y supervisores de obra con expericencia y conocimiento de las regulaciones de INDECI, defensa civil y todas las normas vigentes de seguridad, en se&ntilde;alizacion logramos el equilibrio perfecto entre el dise&ntilde;o creativo y las normas tecnicas para mantener la iamgen de su empresa.";

require_once "header.php";

?>
<link rel='stylesheet' href='css/galeria.css' type='text/css'
	media='all'>
<link rel='stylesheet' id='camera-css' href='css/camera.css'
	type='text/css' media='all'>
<script type="text/javascript" src="/_scripts/jquery-1.7.2.min.js"></script>
<script type='text/javascript' src='/js/jquery.mobile.customized.min.js'></script>
<script type='text/javascript' src='/js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='/js/camera.min.js'></script>
<script type="text/javascript">
$(function(){
	//$("#galeria-titulo").html("Proyecto nueva imagen<br/>");
	$('#slide-bbva').camera({
		height: '400px',
		loader: 'bar',
		pagination: false,
		thumbnails: true,
		time: 4000,
		transPeriod: 1000
	});
	
	$("#galeria-titulo").html("Proyectos de Imagen Corporativa<br/>");
	$("#galeria-titulo").append('<span style="font-size:15px;" >BBVA Banco Continental</span>');
	$("#silde-Banbif").hide();
	$("#silde-cofide").hide();
	$('#menubar a').click(function(){
	});
	
	
	$('#link1').click(function(){
		$("#galeria-titulo").html("Proyectos de Imagen Corporativa<br/>");
		$("#galeria-titulo").append('<span style="font-size:15px;" >BBVA Banco Continental</span>');
		$('#slide-Banbif').fadeOut(500,function(){
			$("#slide-cofide").fadeOut(500,function(){
				$("#slide-Banco_Cencosud").fadeOut(500,function(){
					$('#slide-bbva').fadeIn(500);
				});
			});
		});
	});
	
	$('#link2').click(function(){
		$("#galeria-titulo").html("Proyectos de Imagen Corporativa<br/>");
		$("#galeria-titulo").append('<span style="font-size:15px;" >Banbif</span>');
		//.fadeIn(500);$("#galeria-titulo").fadeOut(500,function(){$(this).text("Centros y/o Agencias de Atención",function(){$(this).fadeIn(500);})});
		$("#slide-bbva").fadeOut(500,function(){
			$("#slide-cofide").fadeOut(500,function(){
				$('#slide-Banco_Cencosud').fadeOut(500,function(){
				$("#slide-Banbif").fadeIn(500,function(){
					
					if( $('#slide-Banbif').is('.loaded') ){}else{

						$('#slide-Banbif').camera({
							height: '400px',
							loader: 'bar',
							pagination: false,
							thumbnails: true,
							time: 4000,
							transPeriod: 1000
						});
						$('#slide-Banbif').addClass("loaded");
					}
				});
			});
			});
		});
		
	});
	
	$('#link3').click(function(){
		$("#galeria-titulo").html("Proyectos de Imagen Corporativa<br/>");
		$("#galeria-titulo").append('<span style="font-size:15px;" >Cofide, Centro de Desarrollo Empresarial</span>');
		$('#slide-Banbif').fadeOut(500,function(){
			$("#slide-bbva").fadeOut(500,function(){
				$('#slide-Banco_Cencosud').fadeOut(500,function(){
				$("#slide-cofide").fadeIn(500,function(){
					
					if( $('#slide-cofide').is('.loaded') ){ }else{
						$('#slide-cofide').camera({
							height: '400px',
							loader: 'bar',
							pagination: false,
							thumbnails: true,
							time: 4000,
							transPeriod: 1000
						});
						$('#slide-cofide').addClass("loaded");
					}
				});
			});
			});
		});
	});
	
	/*$('#link4').click(function(){
		$("#galeria-titulo").html('Proyectos de Imagen Corporativa<br/>');
		$("#galeria-titulo").append('<span style="font-size:15px;" >Banco Cencosud</span>');
		$('#slide-Banbif').fadeOut(500,function(){
			$("#slide-bbva").fadeOut(500,function(){
				$("#slide-cofide").fadeOut(500,function(){
					$('#slide-Banco_Cencosud').fadeIn(500,function(){
					if( $('#slide-Banco_Cencosud').is('.loaded') ){ }else{
						$('#slide-Banco_Cencosud').camera({
							height: '400px',
							loader: 'bar',
							pagination: false,
							thumbnails: true,
							time: 4000,
							transPeriod: 1000
						});
						$('#slide-Banco_Cencosud').addClass("loaded");
					}
				});
			});
			});
		});
	});
	*/	


	
});
</script>

<div id="panel">

	<div class="menubar">
		<ul>
			<li id="link1"><a href="#">BBVA : proyecto nueva imagen </a></li>
			<li id="link2"><a href="#">Banbif : proyecto nueva imagen </a></li>
			<!--  <li id="link4"><a href="#">Banco Cencosud </a></li>-->
			<li id="link3"><a href="#">Cofide : proyecto desarrollo nueva oficina </a></li>
		</ul>
		<div class="btnvolver"></div>
	</div>

	<div id="slider">

		<!--#### BBVA  -->
		<div class="camera_wrap camera_magenta_skin" id="slide-bbva">
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/01.jpg"
				data-src="/_images/_galerias/PIC/BBVA/01.jpg">
				<div class="camera_caption fadeFromBottom">Letras corpóreas nueva imagen</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/02.jpg"
				data-src="/_images/_galerias/PIC/BBVA/02.jpg">
				<div class="camera_caption fadeFromBottom">Letras corpóreas nueva imagen</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/03.jpg"
				data-src="/_images/_galerias/PIC/BBVA/03.jpg">
				<iframe src="https://www.youtube.com/v/ephZeZYq6Pg&autoplay=1"
					width="100%" height="100%" frameborder="0" webkitAllowFullScreen
					mozallowfullscreen allowFullScreen></iframe>
			</div>
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/04.jpg"
				data-src="/_images/_galerias/PIC/BBVA/04.jpg">
				<div class="camera_caption fadeFromBottom">Desarrollo de mobiliario nueva imagen España</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/05.jpg"
				data-src="/_images/_galerias/PIC/BBVA/05.jpg">
				<div class="camera_caption fadeFromBottom">Desarrollo de mobiliario nueva imagen España</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/BBVA/thumbs/06.jpg"
				data-src="/_images/_galerias/PIC/BBVA/06.jpg">
				<div class="camera_caption fadeFromBottom">Desarrollo de mobiliario nueva imagen España</div>
			</div>
		</div>
		<!--#### BBVA  -->

		<!--#### Centros y/o Agencias de Atención  -->
		<div class="camera_wrap camera_magenta_skin" id="slide-Banbif">
			<div data-thumb="/_images/_galerias/PIC/Banbif/thumbs/01.jpg"
				data-src="/_images/_galerias/PIC/Banbif/01.jpg">
				<div class="camera_caption fadeFromBottom">Nueva imagen edificio
					corporativo</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banbif/thumbs/02.jpg"
				data-src="/_images/_galerias/PIC/Banbif/02.jpg">
				<div class="camera_caption fadeFromBottom">Nueva imagen edificio
					corporativo</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banbif/thumbs/03.jpg"
				data-src="/_images/_galerias/PIC/Banbif/03.jpg">
				<div class="camera_caption fadeFromBottom">Vista exterior agencias</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banbif/thumbs/04.jpg"
				data-src="/_images/_galerias/PIC/Banbif/04.jpg">
				<div class="camera_caption fadeFromBottom">Agencias nueva imagen</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banbif/thumbs/05.jpg"
				data-src="/_images/_galerias/PIC/Banbif/05.jpg">
				<div class="camera_caption fadeFromBottom">Agencias nueva imagen</div>
			</div>
		</div>
		<!--#### Tiendas y Retailers  -->


		<!--#### Centros y/o Agencias de Atención  -->
		<div class="camera_wrap camera_magenta_skin" id="slide-Banco_Cencosud">
			<div data-thumb="/_images/_galerias/PIC/Banco_Cencosud/thumbs/01.jpg"
				data-src="/_images/_galerias/PIC/Banco_Cencosud/01.jpg">
				<div class="camera_caption fadeFromBottom">Nuevas oficinas Banco Cencosud</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banco_Cencosud/thumbs/02.jpg"
				data-src="/_images/_galerias/PIC/Banco_Cencosud/02.jpg">
				<div class="camera_caption fadeFromBottom">Nuevas oficinas Banco Cencosud</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banco_Cencosud/thumbs/03.jpg"
				data-src="/_images/_galerias/PIC/Banco_Cencosud/03.jpg">
				<div class="camera_caption fadeFromBottom">Área de atención</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banco_Cencosud/thumbs/04.jpg"
				data-src="/_images/_galerias/PIC/Banco_Cencosud/04.jpg">
				<div class="camera_caption fadeFromBottom">Área de atención</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Banco_Cencosud/thumbs/05.jpg"
				data-src="/_images/_galerias/PIC/Banco_Cencosud/05.jpg">
				<div class="camera_caption fadeFromBottom">Zona atención en caja</div>
			</div>
		</div>
		<!--#### Tiendas y Retailers  -->



		<!--#### Tiendas y Retailers  -->
		<div class="camera_wrap camera_magenta_skin" id="slide-cofide">
			<div data-thumb="/_images/_galerias/PIC/Cofide/thumbs/01.jpg"
				data-src="/_images/_galerias/PIC/Cofide/01.jpg">
				<div class="camera_caption fadeFromBottom">Área de recepción (Centro
					de Desarrollo Empresarial)</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Cofide/thumbs/02.jpg"
				data-src="/_images/_galerias/PIC/Cofide/02.jpg">
				<div class="camera_caption fadeFromBottom">Zona de espera (Centro de
					Desarrollo Empresarial)</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Cofide/thumbs/03.jpg"
				data-src="/_images/_galerias/PIC/Cofide/03.jpg">
				<div class="camera_caption fadeFromBottom">Área de atención (Centro
					de Desarrollo Empresarial)</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Cofide/thumbs/04.jpg"
				data-src="/_images/_galerias/PIC/Cofide/04.jpg">
				<div class="camera_caption fadeFromBottom">Área de acceso a oficinas
					(Centro de Desarrollo Empresarial)</div>
			</div>
			<div data-thumb="/_images/_galerias/PIC/Cofide/thumbs/05.jpg"
				data-src="/_images/_galerias/PIC/Cofide/05.jpg">
				<div class="camera_caption fadeFromBottom">Oficinas (Centro de
					Desarrollo Empresarial)</div>
			</div>
		</div>
		<!--#### Tiendas y Retailers  -->

	</div>
	<!--  -->

</div>

<?include('hacemos_menu.php');?>
<?

require 'footer.php';
?>