<?php
echo $this->headLink ()->prependStylesheet ( $this->basePath ( '/css/themes/default/default.css' ) )->prependStylesheet ( $this->basePath ( '/css/nivo-slider.css' ) )->prependStylesheet ( $this->basePath ( '/css/style-nivo.css' ) );
?>
	
<?php 	echo $this->headScript ()->prependFile ( $this->basePath ("js/jquery.nivo.slider.js")); ?>

<style type="text/css">
.botones a{
	margin-right: 5px;
	margin-left: 5px;
}

</style>



<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>

<div class="row">
	<div class="span12"  style="text-align:center">
	<div id="wrapper">
		<div class="slider-wrapper theme-default">
			<div id="slider" class="nivoSlider">
				<img src='<?php echo $this->basePath ("images-slider/1.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/1.jpg"); ?>'
					alt="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/4.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/2.jpg"); ?>'
					alt="" title="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/3.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/3.jpg"); ?>'
					alt="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/2.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/4.jpg"); ?>'
					alt="" title="" data-transition="slideInLeft" />
			</div>
		</div>
	</div>
	</div>
</div>


<div class="row" >
	<div  class="span12 botones"  style="text-align:center">

		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/tec"
			target="_blank" style="width:200px;"><?php echo $this->translate('Dise&ntilde;o Tiendas y Espacios Comerciales') ?></a>
	
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/pic"
			target="_blank" style="width:200px;"style="width:200px;"style="width:200px;"><?php echo $this->translate('Proyectos de Imagen Corporativa') ?></a>
	
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/tipv"
			target="_blank" style="width:200px;"style="width:200px;"><?php echo $this->translate('Tecnolog&iacute;a e Interactividad ') ?> </a>
	
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/ptm"
			target="_blank" style="width:200px;"><?php echo $this->translate('Proyectos de Trade Marketing') ?></a>
	</div>


</div>
