<?php
echo $this->headLink ()->prependStylesheet ( $this->basePath ( '/css/themes/default/default.css' ) )->prependStylesheet ( $this->basePath ( '/css/nivo-slider.css' ) )->prependStylesheet ( $this->basePath ( '/css/style-nivo.css' ) );
?>
	
<?php 	echo $this->headScript ()->prependFile ( $this->basePath ("js/jquery.nivo.slider.js")); ?>





<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>

<div class="row">
	<div id="wrapper">
		<div class="slider-wrapper theme-default">
			<div id="slider" class="nivoSlider">
				<img src='<?php echo $this->basePath ("images-slider/1.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/1.jpg"); ?>'
					alt="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/4.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/2.jpg"); ?>'
					alt="" title="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/3.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/3.jpg"); ?>'
					alt="" data-transition="slideInLeft" /> <img
					src='<?php echo $this->basePath ("images-slider/2.jpg"); ?>'
					data-thumb='<?php echo $this->basePath ("images-slider/4.jpg"); ?>'
					alt="" title="" data-transition="slideInLeft" />
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="span3">
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/tec"
			target="_blank" style="height: 38px;padding: 4px 20px;"><?php echo $this->translate('TIENDAS Y ESPACIOS COMERCIALES') ?>&raquo;</a>
	</div>
	<div class="span3">
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/pic"
			target="_blank" style="height: 38px;padding: 4px 40px;"><?php echo $this->translate('PROYECTOS DE IMAGEN CORPOTARIVA') ?> &raquo;</a>
	</div>

	<div class="span3">
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/tipv"
			target="_blank" style="height: 38px;"><?php echo $this->translate('TECNOLOG&Iacute;A E INTERACTIVIDAD PARA PUNTOS DE VENTA') ?> &raquo;</a>
	</div>

	<div class="span3">
		<a class="btn btn-success" href="<?=$this->url("projects"); ?>/ptm"
			target="_blank" style="height: 38px;padding: 4px 40px; "><?php echo $this->translate('PROYECTOS DE TRADE MARKETING') ?> &raquo;</a>
	</div>


</div>