



<div class="row">

<div class="span6" id="formulario"> 

<h1>Contáctanos</h1>
<h5>Tell us what do you need by filling this form or call us to (51 1) 717 5333. </h5>
<!--<h5>Dinos lo que necesitas para poder ayudarte llenando este</h5><h5> formulario o llámanos al (51 1) 717 5333.</h5>-->
<br/>
<table>

<tr><td><label for="nombres">Nombres y Apellidos</label></td><td><input type="text" name="nombres" /></td></tr>
<tr><td><label for="email">Email</label></td>
  <td class="input-prepend" style="padding-bottom: 15px;">
      <span class="add-on"><i class="icon-envelope"></i></span>
      <input style="width:176px" id="inputIcon" type="email" name="email" required />
  </td>
</tr>
<tr><td><label for="asunto">Asunto</label></td><td><input type="text" name="asunto" /></td></tr>
<tr><td><label for="mensaje">Mensaje</label></td><td><textarea rows="3"></textarea></td></tr>
<tr><td><label for="empresa">Empresa</label></td><td><input type="text" name="empresa" /></td></tr>
<tr><td><label for="telefono">Teléfono</label></td><td><input type="text" name="telefono" /></td></tr>
<tr><td align="right"><button type="button" class="btn" id="enviar">Enviar</button><td><button type="button" class="btn" id="cancelar">Cancelar</button></td></tr>

</table>

</div>

<div id="map-canvas" class="span6"></div>

</div>


<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfH4BYo1oPQSNDBz7ogOjH-RT5bSPMdBY&sensor=false">
</script>
<script type="text/javascript">
     function initialize() {
     	var latlng = new google.maps.LatLng(-12.209932, -76.977362);

        var mapOptions = {
          center: latlng,
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        var marker = new google.maps.Marker({
        	position: latlng, 
        	map: map,
        	title:"Apoyo Publicitario"
        });


      }
      google.maps.event.addDomListener(window, 'load', initialize);



     $(document).ready(function() {
        $("#cancelar").click(function(){
          console.log( $("#formulario input"));
          $("#formulario textarea").val("");
          $("#formulario input").each(function() {
            $(this).val("");
          });
        });

         $("#enviar").click(function(){
            console.log( $("input[name=nombres]").val() );


            

         });
    });




</script>

<style type="text/css">

#map-canvas {
   display: block;
   height: 480px;
   margin-top: 20px; 
}


div#formulario table {
  margin: .6em 0;
  /*border-collapse: collapse;*/
  width: 100%;
}

div#formulario table td,div#formulario table th {
  border: 1px solid #fff;
  padding: .3em 3px;
  margin: 2px;
  
  font-size: .8em;
}

div#formulario table th {
  background: #AAA;
}


</style>


