
<link rel='stylesheet' id='camera-css' href='css/camera.css'
	type='text/css' media='all'>


<style>
#slider_index { /*margin-right: 100px;*/
	
}

.botones img {
	margin: 10px auto;
}

.botones h4 {
	font-size: 13px;
	text-align: center;
}

.botones p {
	text-align: center;
}

.navbar-inner{
	/*background: none;*/
}

.navbar .container{
	margin: 0 auto;
}
/*FB*/
div#fb_color {
	font-family: 'lucida grande', tahoma, verdana, arial, sans-serif;
	font-size: 13px;
	color: #333333;
	padding: 10px 12px;
	border-top: solid 1px #315C99;
	border-left: solid 1px #AAAAAA;
	border-right: solid 1px #AAAAAA;
	border-bottom: solid 1px #C6CEDD;
	background: #EDEFF4;
	line-height: 1.28;
	font-weight: bold;
}

#fb-root {
	display: none;
}

/* To fill the container and nothing else */
.fb_iframe_widget,.fb_iframe_widget span,.fb_iframe_widget span iframe[style]
	{
	width: 100% !important;
}
/*Peru Retail Widget*/
div#peruretail {
	border: solid 1px #1799CA;
}

div#pr-logo {
	border-bottom: solid 1px #1799CA;
}

div#text_retail {
	font-weight: bold;
	color: #1799CA;
	font-size: 12px;
	font-family: Trebuchet MS;
/*	float: right;
	padding: 10px;*/
	float: right;
	margin: 5px 10px;
}

div#pr-logo img {
	margin: 0 0 0 12px;
	border: none;
}

div#pr-noticias {
	padding: 8px;
	height: 448px;
	color: #666666;
}

div#pr-noticias h1 a,div#pr-noticias h2 a {
	font-family: "Times New Roman", "Georgia";
	font-weight: normal;
	color: #1799CA;
	font-size: 15px;
	font-weight: bold;
	line-height: 10px;
	text-decoration: none;
}

div#pr-noticias p.links a {
	color: #1799CA;
	text-decoration: none;
}

div#pr-noticias p {
	font-size: 10px;
}
</style>
<script type='text/javascript' src='js/jquery.min.js'></script>
<script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
<script type='text/javascript' src='js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='js/camera.min.js'></script>

<script>
		jQuery(function(){
			
			jQuery('#camera_wrap_1').camera({
				thumbnails: true,
				time: 3000,
				height: '40%'
			});
//application/index/peruretail

			$.ajax({
				  url: 'application/index/peruretail',
				  success: function(data) {
				    $('#pr-noticias').html(data).css("overflow-y","scroll");
				    $('#pr-noticias h1').css("line-height", "18px");
				    $('#pr-noticias h2').css("line-height", "18px");
				    $('#pr-noticias img').css("height", "50%").css("width", "50%");
				    
				   	//alert('Load was performed.');
				  },
				  error:
					  function() { $('#pr-noticias').html("Error!"); }
				});

			
		});


</script>

<!-- Slider! -->
<div class="row">
	<div class="span12">
		<section id="slider_index">
			<div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
				<div data-thumb="images-slider/slide01-small2.png"
					data-src="images-slider/slide01.png" data-link="/projects/tec">
					<div class="camera_caption fadeFromBottom"><?php echo $this->translate('Tiendas y Espacios Comerciales'); ?></div>
				</div>
				<div data-thumb="images-slider/slide04-small2.png"
					data-src="images-slider/slide04.png" data-link="/projects/pic">
					<div class="camera_caption fadeFromBottom"><?php echo $this->translate('Proyectos de Imagen Corporativa') ?></div>
				</div>
				<div data-thumb="images-slider/slide03-small2.png"
					data-src="images-slider/slide03.png" data-link="/projects/tipv">
					<div class="camera_caption fadeFromBottom"><?php echo $this->translate('Tecnolog&iacute;a e interactividad para puntos de venta') ?></div>
				</div>

				<div data-thumb="images-slider/slide-ptm-small.png"
					data-src="images-slider/slide-ptm.png" data-link="/projects/ptm">
					<div class="camera_caption fadeFromBottom"><?php echo $this->translate('Proyectos de Trade Marketing') ?></div>
				</div>

				<div data-thumb="images-slider/slide05-small.png"
					data-src="images-slider/slide05.png" data-link="/stands">
					<div class="camera_caption fadeFromBottom"><?php echo $this->translate('Stands/Exhibits') ?></div>
				</div>



			</div>
		</section>
	</div>
</div>
<!-- !Slider -->

<div class="row">

	<div class="span5">

		<div id="fb-root"></div>
		<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '361280773935788', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/es_LA/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
	</script>
		<div id="fb_color"><?php echo $this->translate('Cont&aacute;ctanos tambi&eacute;n por Facebook') ?></div>
		<div class="fb-like-box"
			data-href="http://www.facebook.com/apoyopublicitario"
			data-width="350" data-height="450" data-show-faces="true"
			data-stream="true" data-header="false"></div>


	</div>

	<div class="span5">
		<div id="peruretail">
			<div id="pr-logo">
				<a href="http://www.peru-retail.com/" target="_blank"><img
					src="images/peru-retail-small.png" /></a>
				<div id="text_retail"><?php echo $this->translate('Noticias Retail') ?></div>
			</div>
			<div id="pr-noticias">
				<div style="margin: 50% 45%;">
					<img alt="loading" src="images/loading.gif">
				</div>



			</div>
		</div>
	</div>

	<div class="span2 botones">
		<h4><?php // echo $this->translate('Operaciones a nivel nacional y fuera del pa&iacute;s') ?>
		<?=$this->translate('Operaciones Globales') ?>
		
		</h4>
		<p>	<!-- <a href="/stands"><img src="/images/world_map2.gif" /></a> -->
			<a href="/stands"><img src="/images/global.gif" /></a>
		</p>
		<h4><?php echo $this->translate('Nuestros Socios') ?></h4>
		<p>
			<a href="/stands"><img src="/images/NS-2.gif" /></a>
		</p>
		<p>
			<img src="/images/<?php echo $this->translate('contact_es.png') ?>" />
		</p>
	</div>
</div>
