
<link rel='stylesheet' id='camera-css' href='css/camera.css'
	type='text/css' media='all'>


<style>
#slider_index {
	/*margin-right: 100px;*/
}


/*FB*/
div#fb_color {
	font-family: 'lucida grande', tahoma, verdana, arial, sans-serif;
	font-size: 13px;
	color: #333333;
	padding: 10px 12px;
	border-top: solid 1px #315C99;
	border-left: solid 1px #AAAAAA;
	border-right: solid 1px #AAAAAA;
	border-bottom: solid 1px #C6CEDD;
	background: #EDEFF4;
	line-height: 1.28;
	font-weight: bold;
}

#fb-root {
    display: none;
}

/* To fill the container and nothing else */

.fb_iframe_widget, .fb_iframe_widget span, .fb_iframe_widget span iframe[style] {
    width: 100% !important;
}
/*Peru Retail Widget*/
div#peruretail{
	border: solid 1px #1799CA;
}
div#pr-logo {
	border-bottom: solid 1px #1799CA;
}

div#pr-logo div {
	font-weight: bold;
	color: #1799CA;
	font-size: 12px;
	font-family: Trebuchet MS;
	
	float: right;
	padding: 10px;
}

div#pr-logo img {
	margin: 0 0 0 12px;
	border: none;
}

div#pr-noticias {
	padding:8px;
	
	height: 448px;
	color: #666666;
}



div#pr-noticias h1 a,div#pr-noticias h2 a {
	font-family: "Times New Roman", "Georgia";
	font-weight: normal;
	color: #1799CA;
	font-size: 15px;
	font-weight:bold;
	line-height: 10px;
	text-decoration: none;
}

div#pr-noticias p.links a {
	color: #1799CA;
	text-decoration: none;
}

div#pr-noticias p {
	font-size: 10px;
}
</style>
<script type='text/javascript' src='js/jquery.min.js'></script>
<script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
<script type='text/javascript' src='js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='js/camera.min.js'></script>

<script>
		jQuery(function(){
			
			jQuery('#camera_wrap_1').camera({
				thumbnails: true,
				height: '40%'
			});
//application/index/peruretail

			$.ajax({
				  url: 'application/index/peruretail',
				  success: function(data) {
				    $('#pr-noticias').html(data).css("overflow-y","scroll");
				    $('#pr-noticias h1').css("line-height", "18px");
				    $('#pr-noticias h2').css("line-height", "18px");
				    $('#pr-noticias img').css("height", "50%").css("width", "50%");
				    
				   	//alert('Load was performed.');
				  },
				  fail:
					  function() { $('#pr-noticias').html("Error!"); }
				});

			
		});


</script>

<!-- Slider! -->
<div class="row">
	<section id="slider_index">
		<div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
			<div data-thumb="images-slider/slide01-small2.png"
				data-src="images-slider/slide01.png">
				<div class="camera_caption fadeFromBottom">Tiendas y Espacios
					Comerciales</div>
			</div>
			<div data-thumb="images-slider/slide04-small2.png"
				data-src="images-slider/slide04.png">
				<div class="camera_caption fadeFromBottom">Proyectos de Imagen
					Corporativa</div>
			</div>
			<div data-thumb="images-slider/slide03-small2.png"
				data-src="images-slider/slide03.png">
				<div class="camera_caption fadeFromBottom">Tecnología e
					interactividad para puntos de venta</div>
			</div>
			<div data-thumb="images-slider/slide-ptm-small.png"
				data-src="images-slider/slide-ptm.png">
				<div class="camera_caption fadeFromBottom">Proyectos de Trade
					Marketing</div>
			</div>
		</div>
	</section>

</div>
<!-- !Slider -->

<div class="row">

	<div class="span4">

		<div id="fb-root"></div>
		<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '361280773935788', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/es_LA/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
	</script>
		<div id="fb_color">Contáctanos también por Facebook</div>
		<div class="fb-like-box"
			data-href="http://www.facebook.com/apoyopublicitario"
			data-width="350" data-height="450" data-show-faces="true"
			data-stream="true" data-header="false"></div>


	</div>

	<div class="span4">
		<div id="peruretail">
		<div id="pr-logo">
			<a href="http://www.peru-retail.com/" target="_blank"><img
				src="images/peru-retail-small.png" /></a>
			<div style="margin: 0 0 0 0; padding: 15px 0 0 0;">Noticias Retail</div>
		</div>
		<div id="pr-noticias">
			<div style="margin: 50% 45%;"><img alt="loading" src="images/loading.gif" ></div>
		     
		
		
		</div>
		</div>
	</div>

	<div class="span4">
		<h2><?php echo $this->translate('Help &amp; Support') ?></h2>
		<p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk.2 on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk.2">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
		<p>
			<a class="btn btn-success"
				href="http://webchat.freenode.net?channels=zftalk.2" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a>
		</p>
	</div>
</div>
